export enum TIPO_ESTADO_SOLICITUDES {
    CREADO = 'CREADO',
    PAGADO = 'PAGADO',
    VALIDADO = 'VALIDADO',
    ACTIVO = 'ACTIVO',
    SUSPENDIDO = 'SUSPENDIDO',
    DEVOLUCION = 'DEVOLUCION',
    CONSUMIDO = 'CONSUMIDO'
}